name: force_elements
description: >
  The polymer elements for the dart force framework
version: 0.0.3
author: Joris Hermans <hermansj@gmail.com>
homepage: https://github.com/ForceUniverse/force_elements
dependencies:
  polymer: ">=0.16.0+7 <0.17.0"
  force: ">=0.6.3+4 <0.7.0"
  web_components: ">=0.9.0 <0.12.0"
dev_dependencies:
  unittest: any
transformers:
- polymer
