name: force_elements
description: >
  The polymer elements for the dart force framework
version: 0.0.1
author: Joris Hermans
#homepage: https://www.example.com
dependencies:
  polymer: ">=0.16.0+7 <0.17.0"
  force: 
    git: git://github.com/ForceUniverse/dart-force.git
  web_components: ">=0.9.0 <0.12.0"
dev_dependencies:
  unittest: any
transformers:
- polymer
